# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 626)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 183, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 183, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 183, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lblMonero = QtWidgets.QLabel(self.centralWidget)
        self.lblMonero.setGeometry(QtCore.QRect(310, 62, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblMonero.setFont(font)
        self.lblMonero.setObjectName("lblMonero")
        self.lblMoneroinclO = QtWidgets.QLabel(self.centralWidget)
        self.lblMoneroinclO.setGeometry(QtCore.QRect(310, 91, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblMoneroinclO.setFont(font)
        self.lblMoneroinclO.setObjectName("lblMoneroinclO")
        self.lblBitcoin = QtWidgets.QLabel(self.centralWidget)
        self.lblBitcoin.setGeometry(QtCore.QRect(310, 120, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblBitcoin.setFont(font)
        self.lblBitcoin.setObjectName("lblBitcoin")
        self.lblEthereum = QtWidgets.QLabel(self.centralWidget)
        self.lblEthereum.setGeometry(QtCore.QRect(310, 149, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblEthereum.setFont(font)
        self.lblEthereum.setObjectName("lblEthereum")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 220, 811, 381))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.OpenOrders = QtWidgets.QWidget()
        self.OpenOrders.setMinimumSize(QtCore.QSize(858, 0))
        self.OpenOrders.setMaximumSize(QtCore.QSize(600, 16777215))
        self.OpenOrders.setBaseSize(QtCore.QSize(0, 0))
        self.OpenOrders.setObjectName("OpenOrders")
        self.OpenOrdersWidget = QtWidgets.QTableWidget(self.OpenOrders)
        self.OpenOrdersWidget.setGeometry(QtCore.QRect(-1, -1, 791, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenOrdersWidget.sizePolicy().hasHeightForWidth())
        self.OpenOrdersWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.OpenOrdersWidget.setFont(font)
        self.OpenOrdersWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OpenOrdersWidget.setAutoFillBackground(False)
        self.OpenOrdersWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OpenOrdersWidget.setLineWidth(1)
        self.OpenOrdersWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.OpenOrdersWidget.setShowGrid(True)
        self.OpenOrdersWidget.setGridStyle(QtCore.Qt.DashLine)
        self.OpenOrdersWidget.setCornerButtonEnabled(True)
        self.OpenOrdersWidget.setObjectName("OpenOrdersWidget")
        self.OpenOrdersWidget.setColumnCount(5)
        self.OpenOrdersWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.OpenOrdersWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.OpenOrdersWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.OpenOrdersWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.OpenOrdersWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.OpenOrdersWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.OpenOrdersWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.OpenOrdersWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OpenOrdersWidget.setItem(4, 2, item)
        self.OpenOrdersWidget.horizontalHeader().setDefaultSectionSize(151)
        self.tabWidget.addTab(self.OpenOrders, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.HistoryWidget = QtWidgets.QTableWidget(self.History)
        self.HistoryWidget.setGeometry(QtCore.QRect(-1, -1, 791, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistoryWidget.sizePolicy().hasHeightForWidth())
        self.HistoryWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.HistoryWidget.setFont(font)
        self.HistoryWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HistoryWidget.setAutoFillBackground(False)
        self.HistoryWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HistoryWidget.setLineWidth(1)
        self.HistoryWidget.setShowGrid(True)
        self.HistoryWidget.setGridStyle(QtCore.Qt.DashLine)
        self.HistoryWidget.setCornerButtonEnabled(True)
        self.HistoryWidget.setObjectName("HistoryWidget")
        self.HistoryWidget.setColumnCount(5)
        self.HistoryWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.HistoryWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.HistoryWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.HistoryWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.HistoryWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        item.setFont(font)
        self.HistoryWidget.setHorizontalHeaderItem(4, item)
        self.HistoryWidget.horizontalHeader().setDefaultSectionSize(151)
        self.tabWidget.addTab(self.History, "")
        self.Trading = QtWidgets.QWidget()
        self.Trading.setObjectName("Trading")
        self.layoutWidget = QtWidgets.QWidget(self.Trading)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 42, 139, 85))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lnSellPrice = QtWidgets.QLineEdit(self.layoutWidget)
        self.lnSellPrice.setObjectName("lnSellPrice")
        self.verticalLayout_7.addWidget(self.lnSellPrice)
        self.lnSellAmount = QtWidgets.QLineEdit(self.layoutWidget)
        self.lnSellAmount.setObjectName("lnSellAmount")
        self.verticalLayout_7.addWidget(self.lnSellAmount)
        self.lnSellTotal = QtWidgets.QLineEdit(self.layoutWidget)
        self.lnSellTotal.setObjectName("lnSellTotal")
        self.verticalLayout_7.addWidget(self.lnSellTotal)
        self.buyButton = QtWidgets.QPushButton(self.Trading)
        self.buyButton.setGeometry(QtCore.QRect(198, 140, 93, 28))
        self.buyButton.setObjectName("buyButton")
        self.sellButton = QtWidgets.QPushButton(self.Trading)
        self.sellButton.setGeometry(QtCore.QRect(548, 140, 93, 28))
        self.sellButton.setObjectName("sellButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.Trading)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 20, 101, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblBuy = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBuy.setFont(font)
        self.lblBuy.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblBuy.setObjectName("lblBuy")
        self.verticalLayout_3.addWidget(self.lblBuy)
        self.lblBuyPrice = QtWidgets.QLabel(self.layoutWidget1)
        self.lblBuyPrice.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblBuyPrice.setObjectName("lblBuyPrice")
        self.verticalLayout_3.addWidget(self.lblBuyPrice)
        self.lblBuyAmount = QtWidgets.QLabel(self.layoutWidget1)
        self.lblBuyAmount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblBuyAmount.setObjectName("lblBuyAmount")
        self.verticalLayout_3.addWidget(self.lblBuyAmount)
        self.lblBuyTotal = QtWidgets.QLabel(self.layoutWidget1)
        self.lblBuyTotal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblBuyTotal.setObjectName("lblBuyTotal")
        self.verticalLayout_3.addWidget(self.lblBuyTotal)
        self.layoutWidget2 = QtWidgets.QWidget(self.Trading)
        self.layoutWidget2.setGeometry(QtCore.QRect(390, 20, 101, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblSell = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSell.setFont(font)
        self.lblSell.setObjectName("lblSell")
        self.verticalLayout_5.addWidget(self.lblSell)
        self.lblSellPrice = QtWidgets.QLabel(self.layoutWidget2)
        self.lblSellPrice.setObjectName("lblSellPrice")
        self.verticalLayout_5.addWidget(self.lblSellPrice)
        self.lblSellAmount = QtWidgets.QLabel(self.layoutWidget2)
        self.lblSellAmount.setObjectName("lblSellAmount")
        self.verticalLayout_5.addWidget(self.lblSellAmount)
        self.lblSellTotal = QtWidgets.QLabel(self.layoutWidget2)
        self.lblSellTotal.setObjectName("lblSellTotal")
        self.verticalLayout_5.addWidget(self.lblSellTotal)
        self.layoutWidget3 = QtWidgets.QWidget(self.Trading)
        self.layoutWidget3.setGeometry(QtCore.QRect(150, 42, 139, 85))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lnBuyPrice = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lnBuyPrice.setObjectName("lnBuyPrice")
        self.verticalLayout_6.addWidget(self.lnBuyPrice)
        self.lnBuyAmount = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lnBuyAmount.setObjectName("lnBuyAmount")
        self.verticalLayout_6.addWidget(self.lnBuyAmount)
        self.lnBuyTotal = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lnBuyTotal.setObjectName("lnBuyTotal")
        self.verticalLayout_6.addWidget(self.lnBuyTotal)
        self.tabWidget.addTab(self.Trading, "")
        self.Configuration = QtWidgets.QWidget()
        self.Configuration.setObjectName("Configuration")
        self.saveButton = QtWidgets.QPushButton(self.Configuration)
        self.saveButton.setGeometry(QtCore.QRect(590, 120, 93, 28))
        self.saveButton.setDefault(False)
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.layoutWidget4 = QtWidgets.QWidget(self.Configuration)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 30, 91, 66))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblPoloniex = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPoloniex.setFont(font)
        self.lblPoloniex.setObjectName("lblPoloniex")
        self.verticalLayout_8.addWidget(self.lblPoloniex)
        self.lblPublicKey = QtWidgets.QLabel(self.layoutWidget4)
        self.lblPublicKey.setObjectName("lblPublicKey")
        self.verticalLayout_8.addWidget(self.lblPublicKey)
        self.lblSecretKey = QtWidgets.QLabel(self.layoutWidget4)
        self.lblSecretKey.setObjectName("lblSecretKey")
        self.verticalLayout_8.addWidget(self.lblSecretKey)
        self.layoutWidget5 = QtWidgets.QWidget(self.Configuration)
        self.layoutWidget5.setGeometry(QtCore.QRect(150, 50, 531, 55))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lnPublicKey = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lnPublicKey.setObjectName("lnPublicKey")
        self.verticalLayout_9.addWidget(self.lnPublicKey)
        self.lnSecretKey = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lnSecretKey.setObjectName("lnSecretKey")
        self.verticalLayout_9.addWidget(self.lnSecretKey)
        self.tabWidget.addTab(self.Configuration, "")
        self.lblMyBalances = QtWidgets.QLabel(self.centralWidget)
        self.lblMyBalances.setGeometry(QtCore.QRect(310, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.lblMyBalances.setFont(font)
        self.lblMyBalances.setObjectName("lblMyBalances")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(21, 22, 85, 171))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.layoutWidget6.setFont(font)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCurrency = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblCurrency.setFont(font)
        self.lblCurrency.setObjectName("lblCurrency")
        self.verticalLayout.addWidget(self.lblCurrency)
        self.lblPriceBTC = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblPriceBTC.setFont(font)
        self.lblPriceBTC.setObjectName("lblPriceBTC")
        self.verticalLayout.addWidget(self.lblPriceBTC)
        self.lblPriceUSD = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblPriceUSD.setFont(font)
        self.lblPriceUSD.setObjectName("lblPriceUSD")
        self.verticalLayout.addWidget(self.lblPriceUSD)
        self.lblHigh = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblHigh.setFont(font)
        self.lblHigh.setObjectName("lblHigh")
        self.verticalLayout.addWidget(self.lblHigh)
        self.lblLow = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblLow.setFont(font)
        self.lblLow.setObjectName("lblLow")
        self.verticalLayout.addWidget(self.lblLow)
        self.lblChange = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.lblChange.setFont(font)
        self.lblChange.setObjectName("lblChange")
        self.verticalLayout.addWidget(self.lblChange)
        self.layoutWidget7 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(121, 21, 131, 169))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lnCurrency = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnCurrency.setObjectName("lnCurrency")
        self.verticalLayout_2.addWidget(self.lnCurrency)
        self.lnPriceBTC = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnPriceBTC.setObjectName("lnPriceBTC")
        self.verticalLayout_2.addWidget(self.lnPriceBTC)
        self.lnPriceUSD = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnPriceUSD.setObjectName("lnPriceUSD")
        self.verticalLayout_2.addWidget(self.lnPriceUSD)
        self.lnHigh = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnHigh.setObjectName("lnHigh")
        self.verticalLayout_2.addWidget(self.lnHigh)
        self.lnLow = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnLow.setObjectName("lnLow")
        self.verticalLayout_2.addWidget(self.lnLow)
        self.lnChange = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lnChange.setObjectName("lnChange")
        self.verticalLayout_2.addWidget(self.lnChange)
        self.layoutWidget8 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(503, 57, 181, 115))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lcdMonero = QtWidgets.QLCDNumber(self.layoutWidget8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdMonero.setPalette(palette)
        self.lcdMonero.setAutoFillBackground(False)
        self.lcdMonero.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdMonero.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdMonero.setSmallDecimalPoint(False)
        self.lcdMonero.setDigitCount(15)
        self.lcdMonero.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdMonero.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMonero.setObjectName("lcdMonero")
        self.verticalLayout_4.addWidget(self.lcdMonero)
        self.lcdMoneroinclO = QtWidgets.QLCDNumber(self.layoutWidget8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdMoneroinclO.setPalette(palette)
        self.lcdMoneroinclO.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdMoneroinclO.setDigitCount(15)
        self.lcdMoneroinclO.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMoneroinclO.setObjectName("lcdMoneroinclO")
        self.verticalLayout_4.addWidget(self.lcdMoneroinclO)
        self.lcdBitcoin = QtWidgets.QLCDNumber(self.layoutWidget8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdBitcoin.setPalette(palette)
        self.lcdBitcoin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdBitcoin.setDigitCount(15)
        self.lcdBitcoin.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdBitcoin.setObjectName("lcdBitcoin")
        self.verticalLayout_4.addWidget(self.lcdBitcoin)
        self.lcdEthereum = QtWidgets.QLCDNumber(self.layoutWidget8)
        self.lcdEthereum.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 57, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 27, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 14, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdEthereum.setPalette(palette)
        self.lcdEthereum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdEthereum.setDigitCount(15)
        self.lcdEthereum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdEthereum.setObjectName("lcdEthereum")
        self.verticalLayout_4.addWidget(self.lcdEthereum)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.lblMonero.raise_()
        self.lblMoneroinclO.raise_()
        self.lblBitcoin.raise_()
        self.lblEthereum.raise_()
        self.tabWidget.raise_()
        self.lblMyBalances.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblMonero.setText(_translate("MainWindow", "Monero:"))
        self.lblMoneroinclO.setText(_translate("MainWindow", "Monero incl. open orders:"))
        self.lblBitcoin.setText(_translate("MainWindow", "Bitcoin:"))
        self.lblEthereum.setText(_translate("MainWindow", "Ethereum:"))
        item = self.OpenOrdersWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order Number"))
        item = self.OpenOrdersWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.OpenOrdersWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price (BTC)"))
        item = self.OpenOrdersWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SAmount (XMR)"))
        item = self.OpenOrdersWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Amount (XMR)"))
        __sortingEnabled = self.OpenOrdersWidget.isSortingEnabled()
        self.OpenOrdersWidget.setSortingEnabled(False)
        self.OpenOrdersWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OpenOrders), _translate("MainWindow", "Open Orders"))
        item = self.HistoryWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Currency"))
        item = self.HistoryWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.HistoryWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.HistoryWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.HistoryWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        self.buyButton.setText(_translate("MainWindow", "Buy"))
        self.sellButton.setText(_translate("MainWindow", "Sell"))
        self.lblBuy.setText(_translate("MainWindow", "Buy"))
        self.lblBuyPrice.setText(_translate("MainWindow", "Price (BTC):"))
        self.lblBuyAmount.setText(_translate("MainWindow", "Amount (XMR):"))
        self.lblBuyTotal.setText(_translate("MainWindow", "Total (BTC)"))
        self.lblSell.setText(_translate("MainWindow", "Sell"))
        self.lblSellPrice.setText(_translate("MainWindow", "Price (BTC):"))
        self.lblSellAmount.setText(_translate("MainWindow", "Amount (XMR):"))
        self.lblSellTotal.setText(_translate("MainWindow", "Total (BTC):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Trading), _translate("MainWindow", "Trading"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.lblPoloniex.setText(_translate("MainWindow", "Poloniex"))
        self.lblPublicKey.setText(_translate("MainWindow", "Public Key:"))
        self.lblSecretKey.setText(_translate("MainWindow", "Secret Key:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Configuration), _translate("MainWindow", "Configuration"))
        self.lblMyBalances.setText(_translate("MainWindow", "My Balances:"))
        self.lblCurrency.setText(_translate("MainWindow", "Currency:"))
        self.lblPriceBTC.setText(_translate("MainWindow", "Price (BTC):"))
        self.lblPriceUSD.setText(_translate("MainWindow", "Price (USD):"))
        self.lblHigh.setText(_translate("MainWindow", "24h High:"))
        self.lblLow.setText(_translate("MainWindow", "24h Low:"))
        self.lblChange.setText(_translate("MainWindow", "24h Change:"))

